### ISSUE TITLE
Make Delete Buttons hideable

### ISSUE THREAD

**Issue by kellerkind87** [rtucek/vue-query-builder#91]
Hi,

is there an easy way to show / hide / disable the delete buttons? It is barely possible to do achieve that with pure css.

it could be possible via config like the dragging disable toggle. for my purposes it would be totaly fineto control it globaly.

Bg

**Comment by rtucek** [comment]
Hi @kellerkind87,

off the top of my head,

```css
.query-builder-child__delete-child {
  display: none;
}
```
should work.
